[package]
name = "batcher_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
tokio-rayon = "2.1.0"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
